# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f822b9dd661e4905af9c948a75fba952388dff294260167d75b76d804f3b082bfbec3e8089a844ba32821e833ff83c134eeb12b229cb58832d5f38caee25b1ff

test:
  secret_key_base: cb79c48b3b8cb0c8067f687a513e3298cb7f5486718f43c7019c17a11fc451ec3567e582817e04003eafe446f40636e2bf212a894ff41e3a1f864c0eab42ca98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
